import shutil
import subprocess
import os.path
import sys
import tempfile
import time
from copy import deepcopy
import numpy as np
import random
from concurrent.futures import ProcessPoolExecutor

from simulator import CancerCellEvolutionSimulator, Genotype
from reconstructor import build_evolution_tree, visualize_tree_plotly, neighbor_joining_full, neighbor_joining_full_cps
from evaluator import grf_tree
from evaluator_full import evaluate_4, named_label
from ctbs_utils import to_newick, vizualize_nx_tree

IN_FILE_NAME = "biopsy.txt"
OUT_FILE_NAME = "cnp_distance_matrix.txt"
SIM_DM = "sim_dm.txt"
cnp2cnp_FOLDER = r"/Users/voronwe/Work/PyCharmProjects/cnp2cnp/examples"
cnp2cnp_FILE = r"/Users/voronwe/Work/PyCharmProjects/cnp2cnp/cnp2cnp.py"
TRUE_TREE_ROOT_ID = 0


class Timer:
    def __init__(self, label, collector=None, verbose=False):
        self.label = label
        self.collector = collector  # collector is a dict for the current run
        self.verbose = verbose

    def __enter__(self):
        self.start = time.perf_counter_ns()
        return self

    def __exit__(self, *args):
        duration = time.perf_counter_ns() - self.start
        if self.collector is not None:
            self.collector[self.label] = duration
        if self.verbose:
            print(f"{self.label}: {duration/1e6:.3f} ms")

#  print to file in a format that is compatible with cnp2cnp tool
def to_file(file, cells):
    with open(file, 'w') as f:
        for c in cells:
            f.write(">" + str(c.get_id()) + "\n")
            f.write(c.get_cnp() + "\n")


def _compute_pair(args):
    c, d, i, j  = args
    input_str = f">{c.get_id()}\n{c.get_cnp()}\n>{d.get_id()}\n{d.get_cnp()}\n"
    dist = use_cnp2cnp_to_compute_pairwise_distance(input_str)
    return i, j, dist


def distance_matrix_from_biopsy(cells, max_threads=None):
    """
    Build a distance matrix for a list of cells using cnp2cnp.
    """
    n = len(cells)
    ids = [c.get_id() for c in cells]
    dist_matrix = np.zeros((n, n), dtype=float)

    pairs = [(cells[i], cells[j], i, j) for i in range(n) for j in range(i + 1, n)]

    with ProcessPoolExecutor(max_workers=max_threads) as executor:
        for i, j, dist in executor.map(_compute_pair, pairs):
            dist_matrix[i, j] = dist
            dist_matrix[j, i] = dist

    return ids, dist_matrix


def use_cnp2cnp_to_compute_pairwise_distance(str_in, runfile=cnp2cnp_FILE):
    pypath = str(sys.executable)

    with tempfile.NamedTemporaryFile(mode="w+", delete=False) as tmp:
        tmp.write(str_in)
        tmp.flush()
        infile_path = tmp.name

    out = subprocess.run(
        [pypath, runfile, "-m", "dist", "-i", infile_path],
        capture_output=True, text=True, check=True
    )
    return out.stdout


def use_cnp2cnp_to_compute_dist_matrix(sample=IN_FILE_NAME,
                                       folder=cnp2cnp_FOLDER, runfile=cnp2cnp_FILE,
                                       output=OUT_FILE_NAME):
    """
    Execute cnp2cnp. Input CNPs of cells and obtain evolutionary distance matrix of given cells.

    Parameters
    ----------
    sample : string
        name of the file that contains information about the cell sample; every cell is described in two lines:
        first describing id of the cell, begins with ">" (in example ">cell_0")
        second contains CNP profile as a list of values in a form "value1,value2,...,valueN",
        where N is the length of CNP
    folder : string
        name of the folder that contains cnp2cnp tool described in
        https://doi.org/10.1186/s12864-020-6611-3
        to manually set path where input file will be copied; output file generated before copied back;
    runfile : string
        name of the file to execute (cnp2cnp.py)
        to manually set path to the file
    output : string
        name of the output file that will be generated in location set in argument 'folder',
        and copied to current location.
        first line of the file contains the number N of cells
        the following N lines represent distance matrix, each line consist of the id of the cell
        and N values that are evolutionary distances to the corresponding cells;
        evolutionary distance is the minimal number of events to transform on cell (CNP) to another cell (CNP)

    Returns
    -------
        In the current directory generates a file which name is set in argument 'output'.
        The file will contain distance matrix of cells, which CNPs are given in file described by argument 'input'.
        The file is generated by an external tool cnp2cnp.
    """
    shutil.copy(sample, folder)     # copy file to the cnp2cnp project
    cnp2cnp_in = os.path.join(folder, sample)
    cnp2cnp_out = os.path.join(folder, output)
    pypath = str(sys.executable)
    # compute distance matrix for cnps using cnp2cnp
    subprocess.run([pypath, runfile, "-m", "matrix", "-i", cnp2cnp_in, "-o", cnp2cnp_out])
    # sample use: python cnp2cnp.py -m matrix -i examples/probka1.txt -o examples/o.txt
    shutil.copy(cnp2cnp_out, os.getcwd())   # copy file with results back


def get_cell_manualy(cell_list, value):
    for cell in cell_list:
        if cell.get_id() == value:
            return cell
    return None

def show_cells(cell_list):
    for cell_l in cell_list:
        print("Biopsy: ", [cell.cell_id for cell in cell_l])

def _run_simulation(config, bedfile, seed, simulator_with_loaded_tree, time_collector):
    if simulator_with_loaded_tree:
        return simulator_with_loaded_tree

    if bedfile is not None:
        sim = CancerCellEvolutionSimulator(config, bedfile, seed=seed)
    else:
        sim = CancerCellEvolutionSimulator(config, seed=seed)

    if time_collector is not None:
        with Timer("Core simulation: ", time_collector):
            sim.run_simulation()
    else:
        sim.run_simulation()

    print("Simulation finished. Generated cell evolution tree total nodes:", len(sim.tree.nodes()))
    return sim

def _perform_biopsies(sim, biopsy_generations, biopsy_size, biopsy_size_scalable, seed, compare_dm):
    cell_lists, all_in_one_sample = [], [[]]

    for b_gen in biopsy_generations:
        biopsy = sim.perform_biopsy(
            biopsy_size=biopsy_size,
            biopsy_size_scalable=biopsy_size_scalable,
            generation=b_gen,
            seed=seed
        )
        if biopsy: # we assume biopsy has at least one cell
            cell_lists.append(biopsy)
            all_in_one_sample[0] += biopsy
        else:
            print(f"Biopsy sample from generation {b_gen} has no cells. Skipping.")

    if compare_dm:
        sim.to_distance_matrix(SIM_DM, [x.cell_id for x in all_in_one_sample[0]])

    print("Number of biopsy cells:", len(all_in_one_sample[0]))
    return cell_lists, all_in_one_sample

def _handle_small_biopsy(time_collector):
    print("Total number of cells in biopsy less than 3.")
    if time_collector is not None:
        for key in ["Computing cnp2cnp distance matrix: ", "Clear CNPs: ", "GRF our: ", "GRF NJ: "]:
            time_collector[key] = 0

def _compute_distance_matrix(all_in_one_sample, parallel, time_collector):
    # for parallel case single distances are being computed
    # for not parallel we write biopsy to cnp2cnp format file, and proces that
    unique_cells = list({cell.cell_id: cell for cell in all_in_one_sample[0]}.values())

    if not parallel:
        to_file(IN_FILE_NAME, unique_cells)

    inid = indm = None
    if time_collector is not None:
        with Timer("Computing cnp2cnp distance matrix: ", time_collector):
            if parallel:
                inid, indm = distance_matrix_from_biopsy(unique_cells)
            else:
                use_cnp2cnp_to_compute_dist_matrix(IN_FILE_NAME)
    else:
        if parallel:
            inid, indm = distance_matrix_from_biopsy(unique_cells)
        else:
            use_cnp2cnp_to_compute_dist_matrix(IN_FILE_NAME)
    return inid, indm

def _reconstruct_and_evaluate(sim, seed, cell_lists, all_in_one_sample, r_dist, visualize,
                              clear_cnps, parallel, write_newick, reconstruction_algorithm,
                              inid, indm, time_collector):
    cl, osl = deepcopy(cell_lists), deepcopy(all_in_one_sample)
    show_cells(cell_lists)

    # Optional visualization
    if visualize:
        sim.plot_tree(biopsy_lists=cell_lists, highlight_nodes=all_in_one_sample[0],
                      legend_y_offset=-170, output_file="simulated_tree")

    # # Options for True tree pic
    # only_nodes = [0, 1, 3, 5, 4, 7, 13, 12, 19]
    # if visualize:
    #     sim.plot_tree(biopsy_lists=cell_lists, legend_y_offset=-170,
    #                   highlight_nodes=all_in_one_sample[0], output_file="simulated_tree")
    #     sim.plot_tree(biopsy_lists=cell_lists,legend_y_offset=-170,
    #                   highlight_nodes=all_in_one_sample[0],extended=False,
    #                   only_nodes=only_nodes,node_numbers=True,output_file="true_tree")
    # # if visualize:
    # #     sim.plot_tree(biopsy_lists=cell_lists,legend_y_offset=-170,
    # #                   highlight_nodes=all_in_one_sample[0])

    # # Clear CNPs if requested
    # if clear_cnps:
    #     with Timer("Clear CNPs: ", time_collector) if time_collector else contextlib.nullcontext():
    #         true_tree_simplified = sim.tree_without_CNPs()
    #         for lst in (cl + [osl[0]]):
    #             for cell in lst:
    #                 cell.genome = np.array([], dtype=int)
    # else:
    #     true_tree_simplified = sim.tree

    if clear_cnps:    # clear CNPs
        if time_collector is not None:
            with Timer("Clear CNPs: ", time_collector):
                true_tree_simplified = sim.tree_without_CNPs()  # clears simulated tree
                for cell_list in cl:                            # clears biopsy
                    for cell in cell_list:
                        cell.genome = np.array([], dtype=int)
                for cell in osl[0]:
                    cell.genome = np.array([], dtype=int)
    else:
        true_tree_simplified = sim.tree

    # --- unified build config ---
    build_kwargs = {"r": r_dist}
    build_kwargs.update({"seed": seed})
    if parallel:
        build_kwargs.update({"dist_matrix_path": None, "inids": inid, "indm": indm})
    else:
        build_kwargs.update({"dist_matrix_path": OUT_FILE_NAME})
    if reconstruction_algorithm:
        build_kwargs["neighbor_joining"] = reconstruction_algorithm

    # --- build trees ---
    njtree, nj_info, root_nj = build_evolution_tree(osl, only_nj=True, **build_kwargs)
    tree, rt_info, root_rt = build_evolution_tree(cl, **build_kwargs)

    if write_newick:
        print("Newick simulated:", to_newick(sim.tree))
        print("Reconstructed:", to_newick(tree))
        print("NJ tree:", to_newick(njtree))

    # Visualization (optional)
    if visualize:
        visualize_tree_plotly(tree, rt_info, output_file="reconstructed.html")
        visualize_tree_plotly(njtree, nj_info, output_file="nj.html")

    # if visualize:
    #     lno = {2:[8,6], 1:[20,21,22,25,16,30], 0:[50,32,54,34,56,57,21,38,65,43,71,48]}
    #     visualize_tree_plotly(tree, rt_node_info_for_plots, level_node_ordering=lno, output_file="reconstructed.html")
    #     lno1 = {0:[50,32,54,34,20,56,57,21,22,38,8,65,25,43,16,6,71,30,48]}
    #     visualize_tree_plotly(njtree, nj_node_info_for_plots, level_node_ordering=lno1, output_file="nj.html")


    # --- Evaluate GRF distances ---
    if time_collector is not None:
        with Timer("GRF our: ", time_collector):
            ret1 = grf_tree(true_tree_simplified, TRUE_TREE_ROOT_ID, tree, root_rt)
        with Timer("GRF NJ: ", time_collector):
            ret2 = grf_tree(true_tree_simplified, TRUE_TREE_ROOT_ID, njtree, root_nj)
    else:
        ret1 = grf_tree(true_tree_simplified, TRUE_TREE_ROOT_ID, tree, root_rt)
        ret2 = grf_tree(true_tree_simplified, TRUE_TREE_ROOT_ID, njtree, root_nj)

    print("GRF - reconstructed:", ret1)
    print("GRF - NJ:", ret2)

    return true_tree_simplified, tree, njtree


def run_single_test(config="config_telomeric.json", bedfile="bed like config sample.csv", seed=777,
                    biopsy_size=2, biopsy_size_scalable=None, biopsy_generations=[5,7,9], r_dist=4,
                    visualize=False, time_collector=None, clear_cnps=False, compare_dm=False,
                    write_newick=False, simulator_with_loaded_tree=None, parallel=False,
                    reconstruction_algorithm=None):
    """
    Runs one test that consists of simulation, biopsy, tree reconstruction and tree evaluation.

    Parameters
    ----------
    config  - input configuration file for global parameters for the simulator
    bedfile - optional additional configuration file for positional parameters for the simulator
    seed    - seed for random number generator
    biopsy_size             - size of biopsy (number of cells sampled from given level)
    biopsy_size_scalable    - size of biopsy (percentage of cells sampled from given level)
    biopsy_generatons       - list of levels of the tree (generations numbers) used for biopsy
    r_dist  - the proximity radius for tree reconstruction
    visualize       - whether to visualize the simulation results
    time_collector  - whether to time the simulation runs
    clear_cnps  - whether to clear cnps (potential optimization - makes the simulation tree light)
    compare_dm      - whether to output distance matrix of simulated tree cells
    write_newick       - whether to output simulated tree and reconstructed tree in newick format
    simlulator_with_loaded_tree - for testing and repeatability, simlulator with loaded tree

    Returns
    -------
    The similarity values between simulated tree and reconstructed tree,
    and between simulated tree and NJ-reconstructed tree.

    """
    # 1. Simulation phase
    sim = _run_simulation(config, bedfile, seed, simulator_with_loaded_tree, time_collector)

    # 2. Biopsy phase
    cell_lists, all_in_one_sample = _perform_biopsies(sim, biopsy_generations, biopsy_size,
                                                      biopsy_size_scalable, seed, compare_dm)

    if len(all_in_one_sample[0]) < 3:
        _handle_small_biopsy(time_collector)
        return

    # 3. Distance matrix computation
    inid, indm = _compute_distance_matrix(all_in_one_sample, parallel, time_collector)

    # 4. Tree reconstruction and evaluation
    return _reconstruct_and_evaluate(
        sim,
        seed,
        cell_lists,
        all_in_one_sample,
        r_dist,
        visualize,
        clear_cnps,
        parallel,
        write_newick,
        reconstruction_algorithm,
        inid,
        indm,
        time_collector,
    )


def run_single_test_timed(seed, both=True, **kwargs):
    """
    Wrapper for run_single_test to measure the time for the cases with clear_cnps optimization on and off.

    Parameters
    ----------
    seed        passed to run_single_test
    both        if true executes run_single_test two times with clear_cnps optimization on and off;
                if false executes run_single_test without clear_cnps optimization;
    kwargs      parameters passed to run_single_test

    Returns
    -------
    Dictionaries with times of executions of parts of test (computing distance matrix, GRF distances ...)
    """
    run_timings_no_opt = {}
    with Timer("Total", run_timings_no_opt):
        run_single_test(seed=seed, time_collector=run_timings_no_opt, clear_cnps=False, **kwargs)

    run_timings_with_opt = {}
    if both:
        with Timer("Total", run_timings_with_opt):
            run_single_test(seed=seed, time_collector=run_timings_with_opt, clear_cnps=True, **kwargs)

    return run_timings_no_opt, run_timings_with_opt


def check_clearcnp_optimizaton(how_many=100, both=True, seeds=None, **kwargs):
    """
    Runner

    Parameters
    ----------
    how_many    number of tests to run
    both        if true runs pair of test with clear_cnps optimization on and off;
                otherwise runs one test without optimization
    seeds       seeds for executions of run_single_test; if not given, randomly selected here
    kwargs      parameters passed to run_single_test

    Returns
    -------
    Prints summary of the tests.

    """
    if not seeds:
        seeds = [random.randint(0, 1000) for _ in range(how_many)]
        seeds = [696]

    all_runs_no_opt = []
    all_runs_with_opt = []

    for s in seeds:
        print(f"\nTesting seed: {s}")
        run_no_opt, run_with_opt = run_single_test_timed(seed=s, biopsy_size_scalable=0.5, both=both,
                                                         biopsy_generatons=[4, 6, 8], r_dist=4, **kwargs)
        all_runs_no_opt.append(run_no_opt)
        if both:
            all_runs_with_opt.append(run_with_opt)

    def average_timings(runs):
        all_keys = {k for run in runs for k in run.keys()}
        avg_dict = {}
        for key in sorted(all_keys):
            avg_dict[key] = sum(run.get(key, 0) for run in runs) / len(runs) / 1e6
        without_cnp_avg = sum(
            run["Total"] - run.get("Computing cnp2cnp distance matrix: ", 0) for run in runs
        ) / len(runs) / 1e6
        return avg_dict, without_cnp_avg

    avg_no_opt_dict, avg_no_opt_total = average_timings(all_runs_no_opt)
    if both:
        avg_with_opt_dict, avg_with_opt_total = average_timings(all_runs_with_opt)

    print("\n--- Average durations WITHOUT optimization (ms) ---")
    for k, v in avg_no_opt_dict.items():
        print(f"{k:<35}: {v:.3f}")
    print(f"Total without cnp call{' ' * 10}: {avg_no_opt_total:.3f}")

    if both:
        print("\n--- Average durations WITH optimization (ms) ---")
        for k, v in avg_with_opt_dict.items():
            print(f"{k:<35}: {v:.3f}")
        print(f"Total without cnp call{' ' * 10}: {avg_with_opt_total:.3f}")


if __name__ == "__main__":
    # seeds = [56, 777, 727, 7, 77, 22, 32]
    # for s in seeds:
    #     run_single_test(config="config_telomeric.json", bedfile=None, seed=s,
    #                     biopsy_size=0.5, biopsy_generatons=[5, 7, 9], r_dist=4, visualize=False)

    # r_list = [20, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100]
    # for r in r_list:
    #     print("Running simulation for r=", r)
    #     run_single_test(config="config_telomeric.json", bedfile=None, seed=22,
    #                 biopsy_size=0.5, biopsy_generatons=[5, 7, 9], r_dist=r, visualize=False)

    # timing_data = defaultdict(list)
    # seeds = [56, 777, 7, 77, 22, 32, 727, 0, 100, 1000]
    # for s in seeds:
    #     with Timer("Total", timing_data):
    #         run_single_test(config="config_telomeric.json", bedfile=None, seed=s, biopsy_size=2,
    #                         biopsy_generatons=[4, 7], r_dist=4, visualize=False,
    #                         time_collector=timing_data, clear_cnps=True)
    #
    # print("\nAverage durations (ms):")
    # for key, times in timing_data.items():
    #     avg_ms = sum(times) / len(times) / 1e6
    #     print(f"{key:<15}: {avg_ms:.3f} ms")
    # run_single_test(config="config_for_pic.json", bedfile="pic.csv", seed=727,
    #                 biopsy_size_scalable=0.5, biopsy_generatons=[4, 7], r_dist=4,
    #                 visualize=True)

    # run_single_test(config="config_for_pic.json", bedfile="pic.csv", seed=727,
    #                 biopsy_size_scalable=0.5, biopsy_generatons=[4, 6, 8], r_dist=4,
    #                 visualize=True)

    # run_single_test(seed=727, config="test/data/config_for_pic.json", bedfile="test/data/pic.csv",
    #                       biopsy_size_scalable=0.5, biopsy_generatons=[4, 6, 8], r_dist=4, visualize=True)

    # check_clearcnp_optimizaton(how_many=1, seeds=[773], config="test/data/config_for_pic.json",
    #                            bedfile="test/data/pic.csv", parallel=True, both=False)

    # run_single_test(seed=773, config="test/data/config_for_pic.json",
    #                            bedfile="test/data/pic.csv") #, parallel=True)

    # run_single_test(seed=773, config="test/data/config_for_pic.json", bedfile="test/data/pic.csv",
    #                 biopsy_size_scalable=0.5, biopsy_generations=[4, 6, 8], r_dist=4, write_newick=True,
    #                 reconstruction_algorithm=neighbor_joining_full)

    # seed 35 !!!
    a,b,c = run_single_test(seed=632, config="test/data/config_for_pic.json", bedfile="test/data/pic.csv",
                    biopsy_size_scalable=0.5, biopsy_generations=[4, 6, 8], r_dist=4, write_newick=True,
                    reconstruction_algorithm=neighbor_joining_full_cps)

    out = evaluate_4(a, b, print_debug=True)
    print(out)
    # vizualize_nx_tree(b)

    out = evaluate_4(a, c, print_debug=True)
    # print(out)
    # print(c.edges)
    # print(len(c.nodes))
    # l = [(named_label(c, x), named_label(c, y)) for x, y in c.edges]
    # print(l)
    # roots = [n for n, indeg in c.in_degree() if indeg == 0]
    # if len(roots) != 1:
    #     raise ValueError(f"Tree must have exactly one root (found {len(roots)})")
    # root = roots[0]
    # vizualize_nx_tree(c)

    # run_single_test(seed=773, config="test/data/config_for_pic.json", bedfile="test/data/pic.csv",
    #                 biopsy_size_scalable=0.5, biopsy_generatons=[3, 5, 7, 9], r_dist=4)

    # check_clearcnp_optimizaton(how_many=10, config="test/data/config100.json", bedfile=None)
    # check_clearcnp_optimizaton(how_many=1, config="test/data/config_for_pic.json",
    #                            bedfile=None, both=False, parallel=True)
